translations = {
    "en": {
        "title": "Activity Sentinel",
        "monitoring_settings": "Monitoring Settings",
        "configuration_settings": "Configuration Settings",
        "audio_activity": "Audio Activity",
        "not_detected": "Not Detected",
        "detected": "Detected",
        "gpu_threshold": "GPU Threshold",
        "audio_activity_duration": "Audio Activity Duration (seconds)",
        "audio_volume_threshold": "Audio Volume Threshold",
        "mouse_activity": "Mouse Activity",
        "keyboard_activity": "Keyboard Activity",
        "screen_activity": "Screen Activity",
        "inactivity_time": "Inactivity Time (seconds)",
        "select_inactivity_script": "Select Inactivity Script",
        "no_inactivity_script": "No Inactivity Script Selected",
        "select_activity_script": "Select Activity Script",
        "no_activity_script": "No Activity Script Selected",
        "inactivity_time_label": "Inactivity Time: ",
        "seconds": " seconds",
        "active": "Active",
        "inactive": "Inactive",
        "language": "Language",
        "active_status": "Active Status",
        "inactive_status": "Inactive Status"
    },
    "de": {
        "title": "Aktivitätswächter",
        "monitoring_settings": "Überwachungseinstellungen",
        "configuration_settings": "Konfigurationseinstellungen",
        "audio_activity": "Audioaktivität",
        "not_detected": "Nicht erkannt",
        "detected": "Erkannt",
        "gpu_threshold": "GPU-Schwellenwert",
        "audio_activity_duration": "Audioaktivitätsdauer (Sekunden)",
        "audio_volume_threshold": "Audiolautstärke Schwellenwert",
        "mouse_activity": "Mausaktivität",
        "keyboard_activity": "Tastaturaktivität",
        "screen_activity": "Bildschirmaktivität",
        "inactivity_time": "Inaktivitätszeit (Sekunden)",
        "select_inactivity_script": "Inaktivitätsskript wählen",
        "no_inactivity_script": "Kein Inaktivitätsskript ausgewählt",
        "select_activity_script": "Aktivitätsskript wählen",
        "no_activity_script": "Kein Aktivitätsskript ausgewählt",
        "inactivity_time_label": "Inaktivitätszeit: ",
        "seconds": " Sekunden",
        "active": "Aktiv",
        "inactive": "Inaktiv",
        "language": "Sprache",
        "active_status": "Status Aktiv",
        "inactive_status": "Status Inaktiv"
    }
}
